/**
 * Cross-language parity test for mintWorkspaceAssertion.
 *
 * Verifies that the TS minter produces a byte-identical token to the Python
 * mint_workspace_assertion for the same inputs.  The expected value was
 * generated by running the Python function directly and hard-coded here as a
 * regression anchor — if either minter changes its serialization the test
 * fails immediately.
 *
 * Run with: node apps/web/lib/__tests__/assertion.test.mjs
 */

import assert from 'node:assert/strict'
import { createHmac } from 'node:crypto'

// ---- inline copy of mintWorkspaceAssertion (avoids TypeScript compilation) ---
function mintWorkspaceAssertion({ userId, workspaceId, ttlSeconds, signingKey, issuedAt }) {
  if (!userId || !workspaceId) throw new Error('userId and workspaceId are required')
  if (ttlSeconds <= 0) throw new Error('ttlSeconds must be positive')
  const iat = issuedAt ?? Math.floor(Date.now() / 1000)
  const payloadJson = JSON.stringify({ e: iat + ttlSeconds, u: userId, w: workspaceId })
  const payloadB64 = Buffer.from(payloadJson, 'utf8').toString('base64url')
  const sigB64 = createHmac('sha256', signingKey).update(payloadB64).digest('base64url')
  return `${payloadB64}.${sigB64}`
}

const KEY = 'test-signing-key'
const FIXED_IAT = 1700000000

// Canonical token produced by Python:
//   mint_workspace_assertion(user_id='alice', workspace_id='acme',
//       ttl_seconds=300, signing_key='test-signing-key', issued_at=1700000000)
const PYTHON_TOKEN = 'eyJlIjoxNzAwMDAwMzAwLCJ1IjoiYWxpY2UiLCJ3IjoiYWNtZSJ9.W7IOEnVefvlReZrYlIUiceId9LHPrrjvDNgYtK6mjLo'

// ---- tests ----

assert.equal(
  mintWorkspaceAssertion({ userId: 'alice', workspaceId: 'acme', ttlSeconds: 300, signingKey: KEY, issuedAt: FIXED_IAT }),
  PYTHON_TOKEN,
  'TS token must be byte-identical to Python-minted token (cross-language parity)',
)

assert.throws(
  () => mintWorkspaceAssertion({ userId: '', workspaceId: 'w', ttlSeconds: 60, signingKey: KEY }),
  /userId and workspaceId are required/,
)

assert.throws(
  () => mintWorkspaceAssertion({ userId: 'u', workspaceId: '', ttlSeconds: 60, signingKey: KEY }),
  /userId and workspaceId are required/,
)

assert.throws(
  () => mintWorkspaceAssertion({ userId: 'u', workspaceId: 'w', ttlSeconds: 0, signingKey: KEY }),
  /ttlSeconds must be positive/,
)

assert.throws(
  () => mintWorkspaceAssertion({ userId: 'u', workspaceId: 'w', ttlSeconds: -1, signingKey: KEY }),
  /ttlSeconds must be positive/,
)

// issuedAt override produces a deterministic token
const t1 = mintWorkspaceAssertion({ userId: 'u', workspaceId: 'w', ttlSeconds: 60, signingKey: KEY, issuedAt: FIXED_IAT })
const t2 = mintWorkspaceAssertion({ userId: 'u', workspaceId: 'w', ttlSeconds: 60, signingKey: KEY, issuedAt: FIXED_IAT })
assert.equal(t1, t2, 'same inputs produce same token')

console.log('assertion.test.mjs: all tests passed')
